[package]
name = "moka"
version = "0.5.1"
authors = ["Tatsuya Kawano <tatsuya@hibaridb.org>"]
edition = "2018"

description = "A fast and concurrent cache library inspired by Caffeine (Java) and Ristretto (Go)"
license = "MIT OR Apache-2.0"
# homepage = "https://"
documentation = "https://docs.rs/moka/"
repository = "https://github.com/moka-rs/moka"
keywords = ["cache", "concurrent"]
categories = ["caching", "concurrency"]
readme = "README.md"
exclude = [".devcontainer", ".github", ".vscode"]
build = "build.rs"

# https://docs.rs/about/metadata
[package.metadata.docs.rs]
features = ["future"]

[features]
default = []
future = ["async-io", "async-lock"]

[dependencies]
crossbeam-channel = "0.5"

# moka-cht = { version = "0.6", default-features = false, features = ["hash-arg"] }
moka-cht = { git = "https://github.com/moka-rs/moka-cht", branch = "hash-arg", default-features = false, features = ["hash-arg"] }
# moka-cht = { version = "0.6", path = "../moka-cht", default-features = false, features = ["hash-arg"] }

num_cpus = "1.13"
once_cell = "1.7"
parking_lot = "0.11"
quanta = "0.9"
scheduled-thread-pool = "0.2"
thiserror = "1.0"
uuid = { version = "0.8", features = ["v4"] }

# Optional dependencies
async-io = { version = "1.4", optional = true }
async-lock = { version = "2.4", optional = true }

[dev-dependencies]
actix-rt2 = { package = "actix-rt", version = "2", default-features = false }
actix-rt1 = { package = "actix-rt", version = "1", default-features = false }
async-std = { version = "1", default-features = false, features = ["attributes"] }
futures = "0.3"
getrandom = "0.2"
skeptic = "0.13"
tokio = { version = "1", features = ["rt-multi-thread", "macros" ] }

[target.'cfg(skeptic)'.build-dependencies]
skeptic = "0.13"
